name: Build Staging Version

on:
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest 
    timeout-minutes: 30
    defaults:
      run:
        shell: bash
        working-directory: ./android

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'